/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as RestablecerContrasenaRouteImport } from './routes/restablecer-contrasena'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedJornadaRouteImport } from './routes/_authenticated/jornada'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminAdministradoresRouteImport } from './routes/_authenticated/admin.administradores'
import { Route as AuthenticatedAdminOperariosRouteImport } from './routes/_authenticated/admin.operarios'
import { Route as AuthenticatedOrdenIdRouteImport } from './routes/_authenticated/orden.$id'
import { Route as AuthenticatedAdminOrdenIdRouteImport } from './routes/_authenticated/admin.orden.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const RestablecerContrasenaRoute = RestablecerContrasenaRouteImport.update({
  id: '/restablecer-contrasena',
  path: '/restablecer-contrasena',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJornadaRoute = AuthenticatedJornadaRouteImport.update({
  id: '/jornada',
  path: '/jornada',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAdministradoresRoute =
  AuthenticatedAdminAdministradoresRouteImport.update({
    id: '/administradores',
    path: '/administradores',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOperariosRoute =
  AuthenticatedAdminOperariosRouteImport.update({
    id: '/operarios',
    path: '/operarios',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedOrdenIdRoute = AuthenticatedOrdenIdRouteImport.update({
  id: '/orden/$id',
  path: '/orden/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminOrdenIdRoute =
  AuthenticatedAdminOrdenIdRouteImport.update({
    id: '/orden/$id',
    path: '/orden/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/restablecer-contrasena': typeof RestablecerContrasenaRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/jornada': typeof AuthenticatedJornadaRoute
  '/admin/administradores': typeof AuthenticatedAdminAdministradoresRoute
  '/admin/operarios': typeof AuthenticatedAdminOperariosRoute
  '/orden/$id': typeof AuthenticatedOrdenIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/orden/$id': typeof AuthenticatedAdminOrdenIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/restablecer-contrasena': typeof RestablecerContrasenaRoute
  '/jornada': typeof AuthenticatedJornadaRoute
  '/admin/administradores': typeof AuthenticatedAdminAdministradoresRoute
  '/admin/operarios': typeof AuthenticatedAdminOperariosRoute
  '/orden/$id': typeof AuthenticatedOrdenIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/orden/$id': typeof AuthenticatedAdminOrdenIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/restablecer-contrasena': typeof RestablecerContrasenaRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/jornada': typeof AuthenticatedJornadaRoute
  '/_authenticated/admin/administradores': typeof AuthenticatedAdminAdministradoresRoute
  '/_authenticated/admin/operarios': typeof AuthenticatedAdminOperariosRoute
  '/_authenticated/orden/$id': typeof AuthenticatedOrdenIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/orden/$id': typeof AuthenticatedAdminOrdenIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/restablecer-contrasena'
    | '/admin'
    | '/jornada'
    | '/admin/administradores'
    | '/admin/operarios'
    | '/orden/$id'
    | '/admin/'
    | '/admin/orden/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/restablecer-contrasena'
    | '/jornada'
    | '/admin/administradores'
    | '/admin/operarios'
    | '/orden/$id'
    | '/admin'
    | '/admin/orden/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/restablecer-contrasena'
    | '/_authenticated/admin'
    | '/_authenticated/jornada'
    | '/_authenticated/admin/administradores'
    | '/_authenticated/admin/operarios'
    | '/_authenticated/orden/$id'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/orden/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  RestablecerContrasenaRoute: typeof RestablecerContrasenaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restablecer-contrasena': {
      id: '/restablecer-contrasena'
      path: '/restablecer-contrasena'
      fullPath: '/restablecer-contrasena'
      preLoaderRoute: typeof RestablecerContrasenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jornada': {
      id: '/_authenticated/jornada'
      path: '/jornada'
      fullPath: '/jornada'
      preLoaderRoute: typeof AuthenticatedJornadaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/administradores': {
      id: '/_authenticated/admin/administradores'
      path: '/administradores'
      fullPath: '/admin/administradores'
      preLoaderRoute: typeof AuthenticatedAdminAdministradoresRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/operarios': {
      id: '/_authenticated/admin/operarios'
      path: '/operarios'
      fullPath: '/admin/operarios'
      preLoaderRoute: typeof AuthenticatedAdminOperariosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/orden/$id': {
      id: '/_authenticated/orden/$id'
      path: '/orden/$id'
      fullPath: '/orden/$id'
      preLoaderRoute: typeof AuthenticatedOrdenIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/orden/$id': {
      id: '/_authenticated/admin/orden/$id'
      path: '/orden/$id'
      fullPath: '/admin/orden/$id'
      preLoaderRoute: typeof AuthenticatedAdminOrdenIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAdministradoresRoute: typeof AuthenticatedAdminAdministradoresRoute
  AuthenticatedAdminOperariosRoute: typeof AuthenticatedAdminOperariosRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminOrdenIdRoute: typeof AuthenticatedAdminOrdenIdRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAdministradoresRoute:
    AuthenticatedAdminAdministradoresRoute,
  AuthenticatedAdminOperariosRoute: AuthenticatedAdminOperariosRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminOrdenIdRoute: AuthenticatedAdminOrdenIdRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedJornadaRoute: typeof AuthenticatedJornadaRoute
  AuthenticatedOrdenIdRoute: typeof AuthenticatedOrdenIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedJornadaRoute: AuthenticatedJornadaRoute,
  AuthenticatedOrdenIdRoute: AuthenticatedOrdenIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  RestablecerContrasenaRoute: RestablecerContrasenaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
